sitewomen/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.cache import cache_page

from sitewomen import settings
from women import views
from women.sitemaps import *

sitemaps = {  # Словарь будем передавать в функцию представления sitemap.
    'posts': PostSitemap,
    'cats': CategorySitemap,
}

# Важно заметить, что как только мы добавим хотя бы 1 маршрут, то тестовая стандартная страница Django станет недоступна.
urlpatterns = [
    path('admin/', admin.site.urls),  # Первый параметр определяет суффикс URL-адреса, второй - ссылка на функцию
    # представления, которая будет автоматически вызываться при соответствующем запросе.
    path('', include('women.urls')),  # С помощью функции includes подключаем все маршруты, что были прописаны в пакете
    # приложения в файле urls.py. Если передать суффикс, то он будет добавлен ко всем маршрутам, что мы подключаем.
    path('users/', include('users.urls', namespace='users')),  # namespace - пространство имён для маршрутов users.
    # Таким образом, чтобы обратиться к функции приложения нужно прописать - <пространство имён>:<имя пути>.
    path('__debug__/', include('debug_toolbar.urls')),  # Подключаем url для django debug toolbar.
    path('social-auth/', include('social_django.urls', namespace='social')),  # Подключаем OAuth 2.0.
    path('captcha/', include('captcha.urls')),  # Подключил каптчу.
    path('sitemap.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # Выше формируем карту сайта.
]

if settings.DEBUG:  # Связываем URL с маршрутом в режиме отладки (в боевом режиме сервер и так будет иметь необходимые
    # настройки).
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.page_not_found   # Переменной-перехватчику присваиваем ссылку на функцию представления при 404 ошибке.
# Прим.: все перехватчики исключений работают только при выключенном DEBUG.

admin.site.site_header = 'Панель администрирования'  # Меняем текст хэдера админ-панели.
admin.site.index_title = 'Известные женщины мира'  # Меняем текст подзаголовка панели (тег h1).

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', ProfileUser.as_view(), name='profile'),
]

women/urls.py
from django.urls import path, register_converter
from django.views.decorators.cache import cache_page

from .converters import *
from .views import *

# Все маршруты, которые относятся к приложению women, отдельно вынесены в этот файл.

register_converter(FourDigitYearConverter, 'year4')  # Регистрируем созданный конвертер. Первый аргумент -
# сам конвертер, второй аргумент - имя конвертера для urlpatterns.

urlpatterns = [  # В этой коллекции можно прописать сколько угодно маршрутов для страниц отображения клиенту.
    path('', WomenHome.as_view(), name='home'),  # Кэшируем страницу на 30 секунд.
    path('about/', AboutPage.as_view(), name='about'),
    path('addpage/', AddPage.as_view(), name='add_page'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('post/<slug:post_slug>/', ShowPost.as_view(), name='post'),
    path('category/<slug:cat_slug>/', WomenCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', TagPostList.as_view(), name='tag'),
    path('edit/<slug:slug>/', UpdatePage.as_view(), name='edit_page'),

    # Ниже используются пути и функции для представления базовых возможностей Django.
    path('cats/<int:cat_id>/', categories, name='cats_id'),  # По стандартам отрасли следует прописывать слэш в конце суффикса,
    # ибо если этого не сделать, то вместо привычного 127.0.0.1:8000/cats/ нужно будет писать 127.0.0.1:8000/cats, что неудобно.
    path('cats/<slug:cat_slug>/', categories_by_slug, name='cats'),  # Django проверяет маршруты в порядке их записи,
    # так что int следует ставить раньше, нежели slug, иначе отработает slug.
    # re_path(r'^archive/(?P<year>[0-9]{4})', archive),  # Функция позволяет делать то же самое, что и path, но с
    # использованием регулярных выражений. Полезно, если стандартных конвертеров недостаточно. Но это не лучшее решение,
    # ибо программист не сразу сможет понять, что мы тут обрабатываем, следует использовать отдельный класс в отдельном
    # файле и импортировать этот класс, переписав функцию на классическую path:
    path('archive/<year4:year>/', archive, name='archive'),
    path('main_filters/', main_filters, name='main_filters'),
]

women/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models
from django.urls import reverse


# Create your models here.
class PublishedManager(models.Manager):
    """
    Класс описывает менеджер моделей. Через него модель будет возвращать только опубликованные статьи.\n
    Т.е. доступ к возвращаемому параметру будет доступен в конкретной модели с синтаксисом:\n
    <название модели>.<переменная менеджера в модели>.<метод>\n
    Пример:\n
    Women.published.all()
    """
    def get_queryset(self) -> models.QuerySet:
        """
        Метод возвращает опубликованные статьи.

        :return: QuerySet - коллекция содержит только те записи, у которых флаг публикации = True.
        """
        return super().get_queryset().filter(is_published=Women.Status.PUBLISHED)


def translit_to_eng(s: str) -> str:
    """
    Вспомогательный метод для функции slugify преобразует кириллицу в латиницу с нижним регистром.

    :param s: Начальная строка на кириллице.
    :return: Новая строка в нижнем регистре на латинице.
    """
    d = {'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd',
         'е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i', 'к': 'k',
         'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r',
         'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'c', 'ч': 'ch',
         'ш': 'sh', 'щ': 'shch', 'ь': '', 'ы': 'y', 'ъ': '', 'э': 'e', 'ю': 'yu', 'я': 'ya'}

    return ''.join(map(lambda x: d[x] if d.get(x, False) else x, s.lower()))


class Women(models.Model):
    """
    Класс является связкой для ORM с одноимённой таблицей в БД. Наследование от Model делает наш класс классом модели.

    Атрибуты:\n
    id - PRIMARY KEY, INTEGER, AUTOINCREMENT - главный ключ, формируется автоматически;\n
    title - VARCHAR - обязательное текстовое поле (содержит одну сроку) заголовка (имя женщины), максимальная длина -
    255 символов;\n
    slug - SLUG - обязательное уникальное (unique=True) индексируемое (db_index=True, нужно, чтобы был более быстрый
    выбор статей из БД) поле минимальной длины 5 символов и максимальной длины 100 символов - уникальный идентификатор
    записи;\n
    photo - VARCHAR - необязательное поле, по умолчанию NULL, - фото известной женщины, находящееся в директории по году,
    месяцу и дате добавления;\n
    content - TEXT - необязательное (blank=True) текстовое поле (содержит целое текстовое поле) c содержимым статьи;\n
    time_create - DATETIME - обязательное поле, содержащее время добавления записи в БД, во время первого появления
    конкретной записи автоматически проставляет время (auto_now_add=True);\n
    time_update - DATETIME - обязательное поле, содержащее время обновление записи в БД, автоматически обновляет время
    изменения конкретной записи в БД (auto_now=True);\n
    is_published - BOOLEAN - обязательное поле показывает, опубликована ли статья, по умолчанию все статьи не
    публикуются;\n
    cat - FOREIGN KEY - обязательное поле, запрещает удалять категории, которые связаны с постами, имеет название
    менеджера записей "posts", - внешний ключ таблицы категорий - в БД будет cat_id - "_id" Django добавляет
    самостоятельно. Причём при запросе в ORM cat - выдаст название категории, а при запросе cat_id - выдаст id категории.
    Т.е. cat - это полноценный объект (имеет name и slug), а cat_id - просто int;\n
    tags - MANY TO MANY - необязательное поле имеет название менеджера записей "tags", - внешний ключ таблицы тегов
    (связь многое-ко-многому);\n
    husband - ONE TO ONE - необязательное поле, имеющее название менеджера записей "wuman", по умолчанию ставится NULL -
    внешний ключ таблицы мужа (связь один-к-одному);\n
    objects - стандартный менеджер модели - при добавлении собственного менеджера, атрибут objects автоматически
    затирается, так что следует прописать его явно;\n
    published - кастомный менеджер модели;\n
    author - FOREIGN KEY - обязательное поле, при удалении поста выставляет в таблице значение на NULL, по умолчанию NULL,
    название менеджера записей "posts" - внешний ключ таблицы авторов постов.
    """
    class Status(models.IntegerChoices):
        """
        Вложенный класс перечисления предназначен для определения осмысленных имён значений, содержащихся в коллекции
        класса choices. Т.е. список choices будет состоять из кортежей, которые содержат значение (int) + метка для
        пользователя (str).

        Атрибуты:\n
        DRAFT и PUBLISHED - tuple - кортеж, состоящие из двух элементов: первое значение (int) – это то, которое
        записывается в БД, а второе (str) – это его имя (метка). Фигурируют в коллекции choices (list). DRAFT - константа
        для 0 (False) - черновик. PUBLISHED - константа для 1 (True) - Опубликовано.
        """
        DRAFT = 0, 'Черновик'
        PUBLISHED = 1, 'Опубликовано'

    title = models.CharField(max_length=255, verbose_name='Заголовок', validators=[])
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Slug',
                            validators=[
        MinLengthValidator(5, message='Минимум 5 символов'),
        MaxLengthValidator(100, message='Максимум 100 символов'),
                                        ]
                            )
    photo = models.ImageField(upload_to='photos/%Y-%m-%d', default=None, null=True, blank=True, verbose_name='Фото')
    content = models.TextField(blank=True, verbose_name='Текст статьи')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время обновления')
    is_published = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),
                                       default=Status.DRAFT, verbose_name='Статус')
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='posts', verbose_name='Категория')
    tags = models.ManyToManyField('TagPost', blank=True, related_name='tags', verbose_name='Тег')
    husband = models.OneToOneField('Husband', on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name='woman', verbose_name='Муж')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, related_name='posts', null=True, default=None)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        """
        Вложенный класс предназначен для фильтрации и корректной обработки данных.

        Атрибуты:\n
        verbose_name - str - меняет название ссылки таблицы модели в админ-панели (единственное число);\n
        verbose_name_plural - str - меняет название ссылки таблицы модели в админ-панели (множественное число);\n
        ordering - list - определяет порядок сортировки выбранных записей модели;\n
        indexes - list - определяет столбцы, записи которых должны быть пронумерованы, что позволит ускорить сортировку.
        """
        verbose_name = 'Известные женщины'
        verbose_name_plural = 'Известные женщины'
        ordering = ['-time_create']
        indexes = [
            models.Index(fields=['-time_create']),
        ]

    def __str__(self) -> models.CharField:
        """
        Метод служит для корректного отображения записи из БД.

        :return: Имя женщины.
        """
        return self.title

    def get_absolute_url(self):
        """
        Метод формирует URL-адрес для каждой конкретной записи.

        :return: URL-адрес конкретной записи.
        """
        return reverse('post', kwargs={'post_slug': self.slug})

    # def save(self, *args, **kwargs) -> None:
    #     """
    #     Метод создаёт слаг на основе заголовка статьи и сохраняет запись в БД.
    #     """
    #     self.slug = slugify(translit_to_eng(self.title))
    #     super().save(*args, **kwargs)


class Category(models.Model):
    """
    Класс является связкой для ORM - создаёт таблицу категорий.

    Атрибуты:\n
    name - VARCHAR - обязательное индексируемое поле максимальной длины 100 символов - название категории;\n
    slug - SLUG - обязательное уникальное индексируемое поле максимальной длины 255 символов - уникальный идентификатор
    записи.
    """
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Slug')

    class Meta:
        """
        Вложенный класс предназначен для фильтрации и корректной обработки данных.

        Атрибуты:\n
        verbose_name - str - меняет название ссылки таблицы модели в админ-панели (единственное число);\n
        verbose_name_plural - str - меняет название ссылки таблицы модели в админ-панели (множественное число).
        """
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self) -> models.CharField:
        """
        Метод служит для корректного отображения записи из БД.

        :return: Название категории.
        """
        return self.name

    def get_absolute_url(self):
        """
        Метод формирует URL-адрес для каждой конкретной записи.

        :return: URL-адрес конкретной записи.
        """
        return reverse('category', kwargs={'cat_slug': self.slug})


class TagPost(models.Model):
    """
    Класс модели для тегов.

    Атрибуты:\n
    tag - VARCHAR - обязательное индексируемое текстовое поле длиной 100 символов - тег записи;\n
    slug - SLUG - обязательное индексируемое уникальное поле длиной 255 символов - слаг индекса.
    """
    tag = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def __str__(self) -> models.CharField:
        """
        Метод служит для корректного отображения записи из БД.

        :return: Тег записи.
        """
        return self.tag

    def get_absolute_url(self):
        """

women/templates/women/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>
        Добро пожаловать на мой виртуальный уголок вдохновения и знаний — информационный сайт, посвященный выдающимся
        женщинам мира! Здесь Вы увидите удивительные истории жизни и достижений женщин, чьи вклады оставили
        неизгладимый след в различных сферах общества.<br><br>
        Страницы проекта наполнены биографиями, фотографиями и увлекательными историями, рассказывающими о том,
        как эти невероятные личности преодолевали трудности и воплощали свои мечты. Мой проект — путеводитель в мир
        вдохновения и силы, который призван подчеркнуть роль и влияние женщин на нашу историю и культуру.<br><br>
        От исследования научных свершений до освещения искусства и общественной деятельности, я стремлюсь создать
        место, где каждый посетитель сможет обнаружить что-то новое и вдохновляющее. Я собираю информацию
        из различных источников, чтобы предоставить вам надежные и увлекательные материалы.<br><br>
        Я приглашаю Вас в захватывающее путешествие по миру женской силы и влияния. Давайте вместе откроем тайны,
        изучим истории успеха и восхитимся тем, как женщины меняют мир. Добро пожаловать на мой информационный портал —
        место, где истории женщин становятся вдохновением для всех!
    </p>
    <h3>{{ sub_title }}</h3>
    <p>
        Вы можете указать интересный факт или внести предложения по сайту или содержимому статьи! Для внесения статьи
        перейдите на <a href="{% url 'add_page' %}">форму добавления статьи</a>, а если у Вас есть пожелания, можете
        перейти на <a href="{% url 'contact' %}">форму обратной связи</a> или <a href="{{ contact }}">написать мне</a>.
    </p>
{% endblock %}

women/templates/women/addpage.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><button type="submit">Отправить</button></p>
    </form>
{% endblock %}

women/templates/women/contact.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="post">
        {% include 'users/includes/password_reset_cycle.html' %}
        <button type="submit">Отправить</button>
    </form>
{% endblock %}

women/templates/women/index.html
{% extends 'base.html' %}

{% block content %}
    <ul class="list-articles">
        {% for p in posts %}
            <li>
                <div class="article-panel">
                    <p class="first">Категория: {{ p.cat.name }} | Автор: {{ p.author.username|default:"Неизвестен" }}</p>
                    <p class="last">Дата: {{ p.time_update|date:"d-m-Y H:i:s" }}</p>
                </div>
                {% if p.photo %}
                    <p><img class="img-article-left thumb" src="{{ p.photo.url }}"></p>
                {% endif %}
                <h2>{{ p.title }}</h2>
                {% autoescape off %}
                    {{ p.content|linebreaks|truncatewords:50 }}
                {% endautoescape %}
                <div class="clear"></div>
                <p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}
{% block navigation %}
    {% if page_obj.has_other_pages %}
        <nav class="list-pages">
            <ul>
                {% if page_obj.has_previous %}
                    <li class="page-num">
                        <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
                    </li>
                {% endif %}
                {% for p in paginator.page_range %}
                    {% if page_obj.number == p %}
                        <li class="page-num page-num-selected">{{ p }}</li>
                    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                        <li class="page-num">
                            <a href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-num">
                        <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}

women/templates/women/list_categories.html
{% for cat in cats %}
    {% if cat.id == cat_selected %}
        <li class="selected">{{ cat.name }}</li>
    {% else %}
        <li><a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a></li>
    {% endif %}
{% endfor %}

women/templates/women/list_tags.html
{% if tags %}
    <p>Теги: </p>
    <ul class="tags-list">
        {% for t in tags %}
            <li><a href="{{ t.get_absolute_url }}">{{ t.tag }}</a></li>
        {% endfor %}
    </ul>
{% endif %}

women/templates/women/main_filters.html
<!-- Прописываем маршрут шаблона, от которого наследуемся. -->
{% extends 'base.html' %}

<!-- Всё, что идёт перед блоком контента, будет вставлено и здесь. Ниже исправляем блок контента на нужный нам. -->
{% block content %}
    <!-- Работа с коллекциями несколько отличается в шаблоне от привычного, например, невозможно обратиться к элементу
    списка по индексу. Ещё пример - нельзя обращаться к словарю так: dict['key_1'], требуется обращаться к ключу через точку:
    dict.key_1. С классами аналогично: требуется обращаться к атрибутам класса через точку. Также важно заметить, что
    шаблонизатор игнорирует те параметры, что в нём отсутствуют. И ещё важно понимать, что внутри шаблона нельзя указывать
    более 1 переменной. -->
    <p>{{ menu }}</p>
    <!-- Получаем первый элемент коллекции. -->
    <p>{{ menu|first }}</p>
    <!-- Получаем последний элемент коллекции. -->
    <p>{{ menu|last }}</p>
    <!-- Объединяем все элементы коллекции в строку с помощью разделителя. -->
    <p>{{ menu|join:' | ' }}</p>
    <!-- Фильтр add преобразовал float к целому числу, затем прибавил 50, по итогу получили 78. -->
    <p>{{ float|add:'50' }}</p>
    <!-- Проверяем кратность числа на 2. Предварительно фильтр преобразовал число к целому числу. -->
    <p>{{ float|divisibleby:'2' }}</p>
    <p>{{ lst }}</p>
    <!-- Получаем длину коллекции. -->
    <p>{{ lst|length }}</p>
    <p>{{ set }}</p>
    <p>{{ dict.key_1 }}, {{ dict.key_2 }}</p>
    <p>{{ obj.a }}</p>
    <!-- Переводим строку в слаг. -->
    <p>{{ 'The Main Page'|slugify }}</p>
    <!-- Применили фильтр slugify внутри функции представления. -->
    <p>{{ url }}</p>
    <!-- Первый символ делаем заглавными. -->
    <h1>{{ title|capfirst }}</h1>
    <!-- Все символы делаем заглавными. -->
    <h1>{{ title|upper }}</h1>
    <!-- Все символы делаем строчными. -->
    <h1>{{ title|lower }}</h1>
    <!-- Убираем несколько символов в строке. -->
    <h1>{{ title|cut:' '|cut:'а' }}</h1>
    <!-- Если переменной нет (либо выражение ложное с точки зрения языка Python), то указываем стандартное отображение. -->
    <h1>{{ some_title|default:'Без заголовка' }}</h1>

    <!-- Перебираем элементы коллекции искусственной БД. Синтаксис очень похож на обычный цикл for и условие if в Python. -->
    <ul>
        {% for post in posts %}
            {% if post.is_published %}
                <li>
                    <h2>{{ post.title }}</h2>
                    <p>{{ post.content }}</p>
                </li>
                <!-- У шаблона Django внутри тега for автоматически появляется переменная forloop. -->
                {% if not forloop.last %}
                    <hr>
                {% endif %}
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}

women/templates/women/post.html
{% extends 'base.html' %}

{% block breadcrumbs %}
    {% if perms.women.change_women %}
        <p><a href="{% url 'edit_page' post.slug %}">Редактировать</a></p>
    {% endif %}
    <!-- Теги -->
    {% with post.tags.all as tags %}
        {% if tags %}
            <ul class="tags-list">
                <li>Теги: </li>
                {% for t in tags %}
                    <li><a href="{{ t.get_absolute_url }}">{{ t.tag }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>

    {% if post.photo %}
        <p><img class="img-article-left" src="{{ post.photo.url }}"></p>
    {% endif %}

    {{ post.content|linebreaks }}
{% endblock %}