sitewomen/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.cache import cache_page

from sitewomen import settings
from women import views
from women.sitemaps import *

sitemaps = {  # Словарь будем передавать в функцию представления sitemap.
    'posts': PostSitemap,
    'cats': CategorySitemap,
}

# Важно заметить, что как только мы добавим хотя бы 1 маршрут, то тестовая стандартная страница Django станет недоступна.
urlpatterns = [
    path('admin/', admin.site.urls),  # Первый параметр определяет суффикс URL-адреса, второй - ссылка на функцию
    # представления, которая будет автоматически вызываться при соответствующем запросе.
    path('', include('women.urls')),  # С помощью функции includes подключаем все маршруты, что были прописаны в пакете
    # приложения в файле urls.py. Если передать суффикс, то он будет добавлен ко всем маршрутам, что мы подключаем.
    path('users/', include('users.urls', namespace='users')),  # namespace - пространство имён для маршрутов users.
    # Таким образом, чтобы обратиться к функции приложения нужно прописать - <пространство имён>:<имя пути>.
    path('__debug__/', include('debug_toolbar.urls')),  # Подключаем url для django debug toolbar.
    path('social-auth/', include('social_django.urls', namespace='social')),  # Подключаем OAuth 2.0.
    path('captcha/', include('captcha.urls')),  # Подключил каптчу.
    path('sitemap.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # Выше формируем карту сайта.
]

if settings.DEBUG:  # Связываем URL с маршрутом в режиме отладки (в боевом режиме сервер и так будет иметь необходимые
    # настройки).
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.page_not_found   # Переменной-перехватчику присваиваем ссылку на функцию представления при 404 ошибке.
# Прим.: все перехватчики исключений работают только при выключенном DEBUG.

admin.site.site_header = 'Панель администрирования'  # Меняем текст хэдера админ-панели.
admin.site.index_title = 'Известные женщины мира'  # Меняем текст подзаголовка панели (тег h1).

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', ProfileUser.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    """
    Класс модели предназначен для расширения стандартной модели User.

    Атрибуты:\n
    photo - VARCHAR - необязательное поле фотографии;\n
    date_birth - DATETIME - необязательное поля дня рождения.
    """
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True, null=True, verbose_name='Фотография')
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')

users/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    """
    Класс отвечает за авторизацию и аутентификацию пользователя.

    Атрибуты:\n
    username - VARCHAR - логин пользователя;\n
    password - VARCHAR - пароль пользователя.
    """
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-input'}), label='Логин')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input'}), label='Пароль')
    class Meta:
        """
        Вложенный класс предназначен для корректной обработки данных.

        Атрибуты:\n
        model - models.Model - текущая модель пользователя;\n
        fields - tuple - поля, которые требуется отображать.
        """
        model = get_user_model()
        fields = ('username', 'password')


class RegisterUserForm(UserCreationForm):
    """
    Класс отвечает за регистрацию пользователя.

    Атрибуты:\n
    username - VARCHAR - логин пользователя;\n
    password1 - VARCHAR - пароль пользователя;\n
    password2 - VARCHAR - повтор пароля.
    """
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-input'}), label='Логин')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input'}), label='Пароль')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input'}), label='Повтор пароля')

    class Meta:
        """
        Вложенный класс предназначен для корректной обработки данных.

        Атрибуты:\n
        model - models.Model - текущая модель пользователя;\n
        fields - tuple - поля, которые требуется отображать;\n
        labels - dict - метки для полей;\n
        widgets - dict - CSS-виджеты полей.
        """
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self) -> forms.EmailField:
        """
        Метод-валидатор проверяет уникальность электронной почты.


        :return: Почта.
        :raises ValidationError: Ошибка наличия почты в БД.
        """
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой E-mail уже существует')

        return email


class ProfileUserForm(forms.ModelForm):
    """
    Класс формы предназначен для создания профиля пользователя.

    Атрибуты:\n
    username - VARCHAR - логин пользователя, запрещено для изменения (disabled=True);\n
    email - VARCHAR - почта пользователя, запрещена для изменений, необязательное поле;\n
    this_year - int - сегодняшний год;\n
    date_birth - DATETIME - дата рождения.
    """
    username = forms.CharField(disabled=True, widget=forms.TextInput(attrs={'class': 'form-input'}), label='Логин')
    email = forms.CharField(disabled=True, required=False, widget=forms.TextInput(attrs={'class': 'form-input'}), label='E-mail')
    this_year = datetime.date.today().year
    date_birth = forms.DateTimeField(widget=forms.SelectDateWidget(years=tuple(range(this_year-5, this_year-100, -1))),
                                     label='Дата рождения')

    class Meta:
        """
        Вложенный класс предназначен для корректной обработки данных.

        Атрибуты:\n
        model - models.Model - текущая модель пользователя;\n
        fields - tuple - поля, которые требуется отображать;\n
        labels - dict - метки для полей;\n
        widgets - dict - CSS-виджеты полей.
        """
        model = get_user_model()
        fields = ('photo', 'username', 'email', 'date_birth', 'first_name', 'last_name')
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    """
    Класс формы для смены пароля пользователя.

    Атрибуты:\n
    old_password - VARCHAR - старый пароль;\n
    new_password1 - VARCHAR - новый пароль;\n
    new_password2 - VARCHAR - повтор нового пароля.
    """
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input'}), label='Старый пароль')
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input'}), label='Новый пароль')
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input'}), label='Подтверждение пароля')

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from sitewomen import settings
from users.forms import *


# Create your views here.
class LoginUser(LoginView):
    """
    Класс представления служит для авторизации пользователя.

    Атрибуты:\n
    form_class - forms.AuthenticationForm - класс формы аутентификации пользователя;\n
    template_name - str - имя HTML-шаблона;\n
    extra_context - dict - дополнительный словарь контекста.
    """
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

    # def get_success_url(self):
    #     """
    #     Метод отвечает за перенаправление клиента на определённую страницу при авторизации. Имеет наивысший приоритет
    #     перенаправления клиента.
    #
    #     :return: Ленивое перенаправление на главную страницу.
    #     """
    #     return reverse_lazy('home')


class RegisterUser(CreateView):
    """
    Класс представления отвечает за регистрацию нового пользователя.

    Атрибуты:\n
    form_class - forms.UserCreationForm - класс формы;\n
    template_name - str - HTML-шаблон;\n
    extra_context - dict - дополнительные данные;\n
    success_url - Callable - переход на страницу после успешной регистрации.
    """
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    """
    Класс представления отвечает за отображение профиля пользователя.

    Атрибуты:\n
    model - models.Model - модель;\n
    form_class - forms.ModelForm - класс формы;\n
    template_name - str - HTML-шаблон;\n
    extra_context - dict - дополнительные данные.
    """
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {
        'title': 'Профиль пользователя',
        'default_image': settings.DEFAULT_USER_IMAGE,
    }

    def get_success_url(self):
        """
        Метод отвечает за перенаправление клиента на определённую страницу при изменении и сохранении каких-либо полей
        профиля. Имеет наивысший приоритет перенаправления клиента.

        :return: Ленивое перенаправление на страницу профиля.
        """
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        """
        Метод отбирает ту запись, которая будет отображаться и редактироваться.

        :return: Текущий пользователь.
        """
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    """
    Класс представления служит для отображения страницы смены пароля пользователя.

    Атрибуты:\n
    form_class - forms.ModelForm - класс формы;\n
    success_url - Callable - переход на страницу после успешной регистрации;\n
    template_name - str - HTML-шаблон;\n
    extra_context - dict - дополнительные данные.
    """
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change_form.html'
    extra_context = {'title': 'Смена пароля'}


# Функции представления, заменённые на классы представления:
# def login_user(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
#     """
#     Функция представления служит для авторизации пользователя. В случае успешной авторизации происходит перенаправление
#     на главную страницу.
#
#     :param request: Запрос клиента.
#     :return: Страница авторизации или главная страница.
#     """
#     if request.method == 'POST':
#         form = LoginUserForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user and user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('home'))
#     else:
#         form = LoginUserForm()
#
#     return render(request, 'users/login.html', context={'form': form})
#
#
# def logout_user(request: HttpRequest) -> HttpResponseRedirect:
#     """
#     Функция представления служит для выхода пользователя.
#
#     :param request: Запрос клиента.
#     :return: Перенаправление на страницу авторизации.
#     """
#     logout(request)
#     return HttpResponseRedirect(reverse('users:login'))
#
#
# def register(request: HttpRequest) -> HttpResponse:
#     """
#     Функция представления отвечает за регистрацию нового пользователя.
#
#     :param request: Запрос клиента.
#     :return: Страница регистрации клиента.
#     """
#     if request.method == 'POST':
#         form = RegisterUserForm(request.POST)
#         if form.is_valid():
#             user = form.save(commit=False)
#             user.set_password(form.cleaned_data['password'])
#             user.save()
#             return render(request, 'users/register_done.html')
#     else:
#         form = RegisterUserForm()
#
#     return render(request, 'users/register.html', context={'form': form})

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
        {% include 'users/includes/for_cycle_form.html' %}
        <p><button type="submit">Войти</button></p>
        <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
    </form>
    <hr>
    <p>
        <a href="{% url 'social:begin' 'github' %}"><img src="/media/social-auth/github.png"></a>
        <a href="{% url 'social:begin' 'vk-oauth2' %}"><img src="/media/social-auth/vk.png"></a>
    </p>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}!</h1>
    <p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="post">
        {% csrf_token %}
        {% include 'users/includes/for_cycle_form.html' %}
        <p><button type="submit">Изменить пароль</button></p>
    </form>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для <a href="{% url 'users:login' %}">входа в систему</a>.</p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="post">
        {% include 'users/includes/password_reset_cycle.html' %}
        <p><button type="submit">Сохранить</button></p>
    </form>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
    <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="post">
        {% include 'users/includes/password_reset_cycle.html' %}
        <p><button type="submit">Сбросить по E-mail</button></p>
    </form>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if user.photo %}
            <p><img src="{{ user.photo.url }}"></p>
        {% else %}
            <p><img src="{{ default_image }}"></p>
        {% endif %}
        {% include 'users/includes/for_cycle_form.html' %}
        <p><button type="submit">Сохранить</button></p>
    </form>
    {% if not perms.users.social_auth %}
    <hr>
    <p><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
    {% endif %}
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="text" value="{{ next }}" />
        {% include 'users/includes/for_cycle_form.html' %}
        <p><button type="submit">Регистрация</button></p>
    </form>
{% endblock %}

users/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}
    <h1>Добро пожаловать!</h1>

    <p>Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по
        <a href="{% url 'users:login' %}">ссылке</a>
    </p>
{% endblock %}